# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "D:/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "D:/Program Files/CMake/bin/cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:/Gelis/Programs/Sapphire-Engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:/Gelis/Programs/Sapphire-Engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"D:/Program Files/CMake/bin/cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"D:/Program Files/CMake/bin/cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Gelis/Programs/Sapphire-Engine/CMakeFiles C:/Gelis/Programs/Sapphire-Engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Gelis/Programs/Sapphire-Engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Sapphire-Engine

# Build rule for target.
Sapphire-Engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Sapphire-Engine
.PHONY : Sapphire-Engine

# fast build rule for target.
Sapphire-Engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/build
.PHONY : Sapphire-Engine/fast

# target to build an object file
cmake_pch.hxx.gch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/cmake_pch.hxx.gch
.PHONY : cmake_pch.hxx.gch

# target to preprocess a source file
cmake_pch.hxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/cmake_pch.hxx.i
.PHONY : cmake_pch.hxx.i

# target to generate assembly for a file
cmake_pch.hxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/cmake_pch.hxx.s
.PHONY : cmake_pch.hxx.s

include/Imgui/ImGuiFileDialog.obj: include/Imgui/ImGuiFileDialog.cpp.obj
.PHONY : include/Imgui/ImGuiFileDialog.obj

# target to build an object file
include/Imgui/ImGuiFileDialog.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/ImGuiFileDialog.cpp.obj
.PHONY : include/Imgui/ImGuiFileDialog.cpp.obj

include/Imgui/ImGuiFileDialog.i: include/Imgui/ImGuiFileDialog.cpp.i
.PHONY : include/Imgui/ImGuiFileDialog.i

# target to preprocess a source file
include/Imgui/ImGuiFileDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/ImGuiFileDialog.cpp.i
.PHONY : include/Imgui/ImGuiFileDialog.cpp.i

include/Imgui/ImGuiFileDialog.s: include/Imgui/ImGuiFileDialog.cpp.s
.PHONY : include/Imgui/ImGuiFileDialog.s

# target to generate assembly for a file
include/Imgui/ImGuiFileDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/ImGuiFileDialog.cpp.s
.PHONY : include/Imgui/ImGuiFileDialog.cpp.s

include/Imgui/ImGuizmo.obj: include/Imgui/ImGuizmo.cpp.obj
.PHONY : include/Imgui/ImGuizmo.obj

# target to build an object file
include/Imgui/ImGuizmo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/ImGuizmo.cpp.obj
.PHONY : include/Imgui/ImGuizmo.cpp.obj

include/Imgui/ImGuizmo.i: include/Imgui/ImGuizmo.cpp.i
.PHONY : include/Imgui/ImGuizmo.i

# target to preprocess a source file
include/Imgui/ImGuizmo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/ImGuizmo.cpp.i
.PHONY : include/Imgui/ImGuizmo.cpp.i

include/Imgui/ImGuizmo.s: include/Imgui/ImGuizmo.cpp.s
.PHONY : include/Imgui/ImGuizmo.s

# target to generate assembly for a file
include/Imgui/ImGuizmo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/ImGuizmo.cpp.s
.PHONY : include/Imgui/ImGuizmo.cpp.s

include/Imgui/imgui.obj: include/Imgui/imgui.cpp.obj
.PHONY : include/Imgui/imgui.obj

# target to build an object file
include/Imgui/imgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui.cpp.obj
.PHONY : include/Imgui/imgui.cpp.obj

include/Imgui/imgui.i: include/Imgui/imgui.cpp.i
.PHONY : include/Imgui/imgui.i

# target to preprocess a source file
include/Imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui.cpp.i
.PHONY : include/Imgui/imgui.cpp.i

include/Imgui/imgui.s: include/Imgui/imgui.cpp.s
.PHONY : include/Imgui/imgui.s

# target to generate assembly for a file
include/Imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui.cpp.s
.PHONY : include/Imgui/imgui.cpp.s

include/Imgui/imgui_draw.obj: include/Imgui/imgui_draw.cpp.obj
.PHONY : include/Imgui/imgui_draw.obj

# target to build an object file
include/Imgui/imgui_draw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_draw.cpp.obj
.PHONY : include/Imgui/imgui_draw.cpp.obj

include/Imgui/imgui_draw.i: include/Imgui/imgui_draw.cpp.i
.PHONY : include/Imgui/imgui_draw.i

# target to preprocess a source file
include/Imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_draw.cpp.i
.PHONY : include/Imgui/imgui_draw.cpp.i

include/Imgui/imgui_draw.s: include/Imgui/imgui_draw.cpp.s
.PHONY : include/Imgui/imgui_draw.s

# target to generate assembly for a file
include/Imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_draw.cpp.s
.PHONY : include/Imgui/imgui_draw.cpp.s

include/Imgui/imgui_impl_glfw.obj: include/Imgui/imgui_impl_glfw.cpp.obj
.PHONY : include/Imgui/imgui_impl_glfw.obj

# target to build an object file
include/Imgui/imgui_impl_glfw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_impl_glfw.cpp.obj
.PHONY : include/Imgui/imgui_impl_glfw.cpp.obj

include/Imgui/imgui_impl_glfw.i: include/Imgui/imgui_impl_glfw.cpp.i
.PHONY : include/Imgui/imgui_impl_glfw.i

# target to preprocess a source file
include/Imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_impl_glfw.cpp.i
.PHONY : include/Imgui/imgui_impl_glfw.cpp.i

include/Imgui/imgui_impl_glfw.s: include/Imgui/imgui_impl_glfw.cpp.s
.PHONY : include/Imgui/imgui_impl_glfw.s

# target to generate assembly for a file
include/Imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_impl_glfw.cpp.s
.PHONY : include/Imgui/imgui_impl_glfw.cpp.s

include/Imgui/imgui_impl_opengl3.obj: include/Imgui/imgui_impl_opengl3.cpp.obj
.PHONY : include/Imgui/imgui_impl_opengl3.obj

# target to build an object file
include/Imgui/imgui_impl_opengl3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_impl_opengl3.cpp.obj
.PHONY : include/Imgui/imgui_impl_opengl3.cpp.obj

include/Imgui/imgui_impl_opengl3.i: include/Imgui/imgui_impl_opengl3.cpp.i
.PHONY : include/Imgui/imgui_impl_opengl3.i

# target to preprocess a source file
include/Imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_impl_opengl3.cpp.i
.PHONY : include/Imgui/imgui_impl_opengl3.cpp.i

include/Imgui/imgui_impl_opengl3.s: include/Imgui/imgui_impl_opengl3.cpp.s
.PHONY : include/Imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
include/Imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_impl_opengl3.cpp.s
.PHONY : include/Imgui/imgui_impl_opengl3.cpp.s

include/Imgui/imgui_stdlib.obj: include/Imgui/imgui_stdlib.cpp.obj
.PHONY : include/Imgui/imgui_stdlib.obj

# target to build an object file
include/Imgui/imgui_stdlib.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_stdlib.cpp.obj
.PHONY : include/Imgui/imgui_stdlib.cpp.obj

include/Imgui/imgui_stdlib.i: include/Imgui/imgui_stdlib.cpp.i
.PHONY : include/Imgui/imgui_stdlib.i

# target to preprocess a source file
include/Imgui/imgui_stdlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_stdlib.cpp.i
.PHONY : include/Imgui/imgui_stdlib.cpp.i

include/Imgui/imgui_stdlib.s: include/Imgui/imgui_stdlib.cpp.s
.PHONY : include/Imgui/imgui_stdlib.s

# target to generate assembly for a file
include/Imgui/imgui_stdlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_stdlib.cpp.s
.PHONY : include/Imgui/imgui_stdlib.cpp.s

include/Imgui/imgui_tables.obj: include/Imgui/imgui_tables.cpp.obj
.PHONY : include/Imgui/imgui_tables.obj

# target to build an object file
include/Imgui/imgui_tables.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_tables.cpp.obj
.PHONY : include/Imgui/imgui_tables.cpp.obj

include/Imgui/imgui_tables.i: include/Imgui/imgui_tables.cpp.i
.PHONY : include/Imgui/imgui_tables.i

# target to preprocess a source file
include/Imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_tables.cpp.i
.PHONY : include/Imgui/imgui_tables.cpp.i

include/Imgui/imgui_tables.s: include/Imgui/imgui_tables.cpp.s
.PHONY : include/Imgui/imgui_tables.s

# target to generate assembly for a file
include/Imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_tables.cpp.s
.PHONY : include/Imgui/imgui_tables.cpp.s

include/Imgui/imgui_widgets.obj: include/Imgui/imgui_widgets.cpp.obj
.PHONY : include/Imgui/imgui_widgets.obj

# target to build an object file
include/Imgui/imgui_widgets.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_widgets.cpp.obj
.PHONY : include/Imgui/imgui_widgets.cpp.obj

include/Imgui/imgui_widgets.i: include/Imgui/imgui_widgets.cpp.i
.PHONY : include/Imgui/imgui_widgets.i

# target to preprocess a source file
include/Imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_widgets.cpp.i
.PHONY : include/Imgui/imgui_widgets.cpp.i

include/Imgui/imgui_widgets.s: include/Imgui/imgui_widgets.cpp.s
.PHONY : include/Imgui/imgui_widgets.s

# target to generate assembly for a file
include/Imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/imgui_widgets.cpp.s
.PHONY : include/Imgui/imgui_widgets.cpp.s

include/Imgui/implot.obj: include/Imgui/implot.cpp.obj
.PHONY : include/Imgui/implot.obj

# target to build an object file
include/Imgui/implot.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/implot.cpp.obj
.PHONY : include/Imgui/implot.cpp.obj

include/Imgui/implot.i: include/Imgui/implot.cpp.i
.PHONY : include/Imgui/implot.i

# target to preprocess a source file
include/Imgui/implot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/implot.cpp.i
.PHONY : include/Imgui/implot.cpp.i

include/Imgui/implot.s: include/Imgui/implot.cpp.s
.PHONY : include/Imgui/implot.s

# target to generate assembly for a file
include/Imgui/implot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/implot.cpp.s
.PHONY : include/Imgui/implot.cpp.s

include/Imgui/implot_items.obj: include/Imgui/implot_items.cpp.obj
.PHONY : include/Imgui/implot_items.obj

# target to build an object file
include/Imgui/implot_items.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/implot_items.cpp.obj
.PHONY : include/Imgui/implot_items.cpp.obj

include/Imgui/implot_items.i: include/Imgui/implot_items.cpp.i
.PHONY : include/Imgui/implot_items.i

# target to preprocess a source file
include/Imgui/implot_items.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/implot_items.cpp.i
.PHONY : include/Imgui/implot_items.cpp.i

include/Imgui/implot_items.s: include/Imgui/implot_items.cpp.s
.PHONY : include/Imgui/implot_items.s

# target to generate assembly for a file
include/Imgui/implot_items.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/include/Imgui/implot_items.cpp.s
.PHONY : include/Imgui/implot_items.cpp.s

src/Application/Application.obj: src/Application/Application.cpp.obj
.PHONY : src/Application/Application.obj

# target to build an object file
src/Application/Application.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Application/Application.cpp.obj
.PHONY : src/Application/Application.cpp.obj

src/Application/Application.i: src/Application/Application.cpp.i
.PHONY : src/Application/Application.i

# target to preprocess a source file
src/Application/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Application/Application.cpp.i
.PHONY : src/Application/Application.cpp.i

src/Application/Application.s: src/Application/Application.cpp.s
.PHONY : src/Application/Application.s

# target to generate assembly for a file
src/Application/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Application/Application.cpp.s
.PHONY : src/Application/Application.cpp.s

src/Editor/DebugDraw.obj: src/Editor/DebugDraw.cpp.obj
.PHONY : src/Editor/DebugDraw.obj

# target to build an object file
src/Editor/DebugDraw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/DebugDraw.cpp.obj
.PHONY : src/Editor/DebugDraw.cpp.obj

src/Editor/DebugDraw.i: src/Editor/DebugDraw.cpp.i
.PHONY : src/Editor/DebugDraw.i

# target to preprocess a source file
src/Editor/DebugDraw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/DebugDraw.cpp.i
.PHONY : src/Editor/DebugDraw.cpp.i

src/Editor/DebugDraw.s: src/Editor/DebugDraw.cpp.s
.PHONY : src/Editor/DebugDraw.s

# target to generate assembly for a file
src/Editor/DebugDraw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/DebugDraw.cpp.s
.PHONY : src/Editor/DebugDraw.cpp.s

src/Editor/Editor.obj: src/Editor/Editor.cpp.obj
.PHONY : src/Editor/Editor.obj

# target to build an object file
src/Editor/Editor.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/Editor.cpp.obj
.PHONY : src/Editor/Editor.cpp.obj

src/Editor/Editor.i: src/Editor/Editor.cpp.i
.PHONY : src/Editor/Editor.i

# target to preprocess a source file
src/Editor/Editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/Editor.cpp.i
.PHONY : src/Editor/Editor.cpp.i

src/Editor/Editor.s: src/Editor/Editor.cpp.s
.PHONY : src/Editor/Editor.s

# target to generate assembly for a file
src/Editor/Editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/Editor.cpp.s
.PHONY : src/Editor/Editor.cpp.s

src/Editor/ImGuiWindows.obj: src/Editor/ImGuiWindows.cpp.obj
.PHONY : src/Editor/ImGuiWindows.obj

# target to build an object file
src/Editor/ImGuiWindows.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/ImGuiWindows.cpp.obj
.PHONY : src/Editor/ImGuiWindows.cpp.obj

src/Editor/ImGuiWindows.i: src/Editor/ImGuiWindows.cpp.i
.PHONY : src/Editor/ImGuiWindows.i

# target to preprocess a source file
src/Editor/ImGuiWindows.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/ImGuiWindows.cpp.i
.PHONY : src/Editor/ImGuiWindows.cpp.i

src/Editor/ImGuiWindows.s: src/Editor/ImGuiWindows.cpp.s
.PHONY : src/Editor/ImGuiWindows.s

# target to generate assembly for a file
src/Editor/ImGuiWindows.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/ImGuiWindows.cpp.s
.PHONY : src/Editor/ImGuiWindows.cpp.s

src/Editor/UI/FileExplorer/File.obj: src/Editor/UI/FileExplorer/File.cpp.obj
.PHONY : src/Editor/UI/FileExplorer/File.obj

# target to build an object file
src/Editor/UI/FileExplorer/File.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/UI/FileExplorer/File.cpp.obj
.PHONY : src/Editor/UI/FileExplorer/File.cpp.obj

src/Editor/UI/FileExplorer/File.i: src/Editor/UI/FileExplorer/File.cpp.i
.PHONY : src/Editor/UI/FileExplorer/File.i

# target to preprocess a source file
src/Editor/UI/FileExplorer/File.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/UI/FileExplorer/File.cpp.i
.PHONY : src/Editor/UI/FileExplorer/File.cpp.i

src/Editor/UI/FileExplorer/File.s: src/Editor/UI/FileExplorer/File.cpp.s
.PHONY : src/Editor/UI/FileExplorer/File.s

# target to generate assembly for a file
src/Editor/UI/FileExplorer/File.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/UI/FileExplorer/File.cpp.s
.PHONY : src/Editor/UI/FileExplorer/File.cpp.s

src/Editor/UI/FileExplorer/FileExplorer.obj: src/Editor/UI/FileExplorer/FileExplorer.cpp.obj
.PHONY : src/Editor/UI/FileExplorer/FileExplorer.obj

# target to build an object file
src/Editor/UI/FileExplorer/FileExplorer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/UI/FileExplorer/FileExplorer.cpp.obj
.PHONY : src/Editor/UI/FileExplorer/FileExplorer.cpp.obj

src/Editor/UI/FileExplorer/FileExplorer.i: src/Editor/UI/FileExplorer/FileExplorer.cpp.i
.PHONY : src/Editor/UI/FileExplorer/FileExplorer.i

# target to preprocess a source file
src/Editor/UI/FileExplorer/FileExplorer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/UI/FileExplorer/FileExplorer.cpp.i
.PHONY : src/Editor/UI/FileExplorer/FileExplorer.cpp.i

src/Editor/UI/FileExplorer/FileExplorer.s: src/Editor/UI/FileExplorer/FileExplorer.cpp.s
.PHONY : src/Editor/UI/FileExplorer/FileExplorer.s

# target to generate assembly for a file
src/Editor/UI/FileExplorer/FileExplorer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/UI/FileExplorer/FileExplorer.cpp.s
.PHONY : src/Editor/UI/FileExplorer/FileExplorer.cpp.s

src/Editor/UI/ProjectManager.obj: src/Editor/UI/ProjectManager.cpp.obj
.PHONY : src/Editor/UI/ProjectManager.obj

# target to build an object file
src/Editor/UI/ProjectManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/UI/ProjectManager.cpp.obj
.PHONY : src/Editor/UI/ProjectManager.cpp.obj

src/Editor/UI/ProjectManager.i: src/Editor/UI/ProjectManager.cpp.i
.PHONY : src/Editor/UI/ProjectManager.i

# target to preprocess a source file
src/Editor/UI/ProjectManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/UI/ProjectManager.cpp.i
.PHONY : src/Editor/UI/ProjectManager.cpp.i

src/Editor/UI/ProjectManager.s: src/Editor/UI/ProjectManager.cpp.s
.PHONY : src/Editor/UI/ProjectManager.s

# target to generate assembly for a file
src/Editor/UI/ProjectManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/UI/ProjectManager.cpp.s
.PHONY : src/Editor/UI/ProjectManager.cpp.s

src/Editor/Variables.obj: src/Editor/Variables.cpp.obj
.PHONY : src/Editor/Variables.obj

# target to build an object file
src/Editor/Variables.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/Variables.cpp.obj
.PHONY : src/Editor/Variables.cpp.obj

src/Editor/Variables.i: src/Editor/Variables.cpp.i
.PHONY : src/Editor/Variables.i

# target to preprocess a source file
src/Editor/Variables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/Variables.cpp.i
.PHONY : src/Editor/Variables.cpp.i

src/Editor/Variables.s: src/Editor/Variables.cpp.s
.PHONY : src/Editor/Variables.s

# target to generate assembly for a file
src/Editor/Variables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Editor/Variables.cpp.s
.PHONY : src/Editor/Variables.cpp.s

src/Engine/Engine.obj: src/Engine/Engine.cpp.obj
.PHONY : src/Engine/Engine.obj

# target to build an object file
src/Engine/Engine.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Engine.cpp.obj
.PHONY : src/Engine/Engine.cpp.obj

src/Engine/Engine.i: src/Engine/Engine.cpp.i
.PHONY : src/Engine/Engine.i

# target to preprocess a source file
src/Engine/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Engine.cpp.i
.PHONY : src/Engine/Engine.cpp.i

src/Engine/Engine.s: src/Engine/Engine.cpp.s
.PHONY : src/Engine/Engine.s

# target to generate assembly for a file
src/Engine/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Engine.cpp.s
.PHONY : src/Engine/Engine.cpp.s

src/Engine/Graphics/Animation.obj: src/Engine/Graphics/Animation.cpp.obj
.PHONY : src/Engine/Graphics/Animation.obj

# target to build an object file
src/Engine/Graphics/Animation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Animation.cpp.obj
.PHONY : src/Engine/Graphics/Animation.cpp.obj

src/Engine/Graphics/Animation.i: src/Engine/Graphics/Animation.cpp.i
.PHONY : src/Engine/Graphics/Animation.i

# target to preprocess a source file
src/Engine/Graphics/Animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Animation.cpp.i
.PHONY : src/Engine/Graphics/Animation.cpp.i

src/Engine/Graphics/Animation.s: src/Engine/Graphics/Animation.cpp.s
.PHONY : src/Engine/Graphics/Animation.s

# target to generate assembly for a file
src/Engine/Graphics/Animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Animation.cpp.s
.PHONY : src/Engine/Graphics/Animation.cpp.s

src/Engine/Graphics/Grid.obj: src/Engine/Graphics/Grid.cpp.obj
.PHONY : src/Engine/Graphics/Grid.obj

# target to build an object file
src/Engine/Graphics/Grid.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Grid.cpp.obj
.PHONY : src/Engine/Graphics/Grid.cpp.obj

src/Engine/Graphics/Grid.i: src/Engine/Graphics/Grid.cpp.i
.PHONY : src/Engine/Graphics/Grid.i

# target to preprocess a source file
src/Engine/Graphics/Grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Grid.cpp.i
.PHONY : src/Engine/Graphics/Grid.cpp.i

src/Engine/Graphics/Grid.s: src/Engine/Graphics/Grid.cpp.s
.PHONY : src/Engine/Graphics/Grid.s

# target to generate assembly for a file
src/Engine/Graphics/Grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Grid.cpp.s
.PHONY : src/Engine/Graphics/Grid.cpp.s

src/Engine/Graphics/Renderer.obj: src/Engine/Graphics/Renderer.cpp.obj
.PHONY : src/Engine/Graphics/Renderer.obj

# target to build an object file
src/Engine/Graphics/Renderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer.cpp.obj
.PHONY : src/Engine/Graphics/Renderer.cpp.obj

src/Engine/Graphics/Renderer.i: src/Engine/Graphics/Renderer.cpp.i
.PHONY : src/Engine/Graphics/Renderer.i

# target to preprocess a source file
src/Engine/Graphics/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer.cpp.i
.PHONY : src/Engine/Graphics/Renderer.cpp.i

src/Engine/Graphics/Renderer.s: src/Engine/Graphics/Renderer.cpp.s
.PHONY : src/Engine/Graphics/Renderer.s

# target to generate assembly for a file
src/Engine/Graphics/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer.cpp.s
.PHONY : src/Engine/Graphics/Renderer.cpp.s

src/Engine/Graphics/Renderer/FrameBuffer.obj: src/Engine/Graphics/Renderer/FrameBuffer.cpp.obj
.PHONY : src/Engine/Graphics/Renderer/FrameBuffer.obj

# target to build an object file
src/Engine/Graphics/Renderer/FrameBuffer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/FrameBuffer.cpp.obj
.PHONY : src/Engine/Graphics/Renderer/FrameBuffer.cpp.obj

src/Engine/Graphics/Renderer/FrameBuffer.i: src/Engine/Graphics/Renderer/FrameBuffer.cpp.i
.PHONY : src/Engine/Graphics/Renderer/FrameBuffer.i

# target to preprocess a source file
src/Engine/Graphics/Renderer/FrameBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/FrameBuffer.cpp.i
.PHONY : src/Engine/Graphics/Renderer/FrameBuffer.cpp.i

src/Engine/Graphics/Renderer/FrameBuffer.s: src/Engine/Graphics/Renderer/FrameBuffer.cpp.s
.PHONY : src/Engine/Graphics/Renderer/FrameBuffer.s

# target to generate assembly for a file
src/Engine/Graphics/Renderer/FrameBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/FrameBuffer.cpp.s
.PHONY : src/Engine/Graphics/Renderer/FrameBuffer.cpp.s

src/Engine/Graphics/Renderer/IndexBuffer.obj: src/Engine/Graphics/Renderer/IndexBuffer.cpp.obj
.PHONY : src/Engine/Graphics/Renderer/IndexBuffer.obj

# target to build an object file
src/Engine/Graphics/Renderer/IndexBuffer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/IndexBuffer.cpp.obj
.PHONY : src/Engine/Graphics/Renderer/IndexBuffer.cpp.obj

src/Engine/Graphics/Renderer/IndexBuffer.i: src/Engine/Graphics/Renderer/IndexBuffer.cpp.i
.PHONY : src/Engine/Graphics/Renderer/IndexBuffer.i

# target to preprocess a source file
src/Engine/Graphics/Renderer/IndexBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/IndexBuffer.cpp.i
.PHONY : src/Engine/Graphics/Renderer/IndexBuffer.cpp.i

src/Engine/Graphics/Renderer/IndexBuffer.s: src/Engine/Graphics/Renderer/IndexBuffer.cpp.s
.PHONY : src/Engine/Graphics/Renderer/IndexBuffer.s

# target to generate assembly for a file
src/Engine/Graphics/Renderer/IndexBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/IndexBuffer.cpp.s
.PHONY : src/Engine/Graphics/Renderer/IndexBuffer.cpp.s

src/Engine/Graphics/Renderer/Shader.obj: src/Engine/Graphics/Renderer/Shader.cpp.obj
.PHONY : src/Engine/Graphics/Renderer/Shader.obj

# target to build an object file
src/Engine/Graphics/Renderer/Shader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/Shader.cpp.obj
.PHONY : src/Engine/Graphics/Renderer/Shader.cpp.obj

src/Engine/Graphics/Renderer/Shader.i: src/Engine/Graphics/Renderer/Shader.cpp.i
.PHONY : src/Engine/Graphics/Renderer/Shader.i

# target to preprocess a source file
src/Engine/Graphics/Renderer/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/Shader.cpp.i
.PHONY : src/Engine/Graphics/Renderer/Shader.cpp.i

src/Engine/Graphics/Renderer/Shader.s: src/Engine/Graphics/Renderer/Shader.cpp.s
.PHONY : src/Engine/Graphics/Renderer/Shader.s

# target to generate assembly for a file
src/Engine/Graphics/Renderer/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/Shader.cpp.s
.PHONY : src/Engine/Graphics/Renderer/Shader.cpp.s

src/Engine/Graphics/Renderer/Texture.obj: src/Engine/Graphics/Renderer/Texture.cpp.obj
.PHONY : src/Engine/Graphics/Renderer/Texture.obj

# target to build an object file
src/Engine/Graphics/Renderer/Texture.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/Texture.cpp.obj
.PHONY : src/Engine/Graphics/Renderer/Texture.cpp.obj

src/Engine/Graphics/Renderer/Texture.i: src/Engine/Graphics/Renderer/Texture.cpp.i
.PHONY : src/Engine/Graphics/Renderer/Texture.i

# target to preprocess a source file
src/Engine/Graphics/Renderer/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/Texture.cpp.i
.PHONY : src/Engine/Graphics/Renderer/Texture.cpp.i

src/Engine/Graphics/Renderer/Texture.s: src/Engine/Graphics/Renderer/Texture.cpp.s
.PHONY : src/Engine/Graphics/Renderer/Texture.s

# target to generate assembly for a file
src/Engine/Graphics/Renderer/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/Texture.cpp.s
.PHONY : src/Engine/Graphics/Renderer/Texture.cpp.s

src/Engine/Graphics/Renderer/VertexArray.obj: src/Engine/Graphics/Renderer/VertexArray.cpp.obj
.PHONY : src/Engine/Graphics/Renderer/VertexArray.obj

# target to build an object file
src/Engine/Graphics/Renderer/VertexArray.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/VertexArray.cpp.obj
.PHONY : src/Engine/Graphics/Renderer/VertexArray.cpp.obj

src/Engine/Graphics/Renderer/VertexArray.i: src/Engine/Graphics/Renderer/VertexArray.cpp.i
.PHONY : src/Engine/Graphics/Renderer/VertexArray.i

# target to preprocess a source file
src/Engine/Graphics/Renderer/VertexArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/VertexArray.cpp.i
.PHONY : src/Engine/Graphics/Renderer/VertexArray.cpp.i

src/Engine/Graphics/Renderer/VertexArray.s: src/Engine/Graphics/Renderer/VertexArray.cpp.s
.PHONY : src/Engine/Graphics/Renderer/VertexArray.s

# target to generate assembly for a file
src/Engine/Graphics/Renderer/VertexArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/VertexArray.cpp.s
.PHONY : src/Engine/Graphics/Renderer/VertexArray.cpp.s

src/Engine/Graphics/Renderer/VertexBuffer.obj: src/Engine/Graphics/Renderer/VertexBuffer.cpp.obj
.PHONY : src/Engine/Graphics/Renderer/VertexBuffer.obj

# target to build an object file
src/Engine/Graphics/Renderer/VertexBuffer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/VertexBuffer.cpp.obj
.PHONY : src/Engine/Graphics/Renderer/VertexBuffer.cpp.obj

src/Engine/Graphics/Renderer/VertexBuffer.i: src/Engine/Graphics/Renderer/VertexBuffer.cpp.i
.PHONY : src/Engine/Graphics/Renderer/VertexBuffer.i

# target to preprocess a source file
src/Engine/Graphics/Renderer/VertexBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/VertexBuffer.cpp.i
.PHONY : src/Engine/Graphics/Renderer/VertexBuffer.cpp.i

src/Engine/Graphics/Renderer/VertexBuffer.s: src/Engine/Graphics/Renderer/VertexBuffer.cpp.s
.PHONY : src/Engine/Graphics/Renderer/VertexBuffer.s

# target to generate assembly for a file
src/Engine/Graphics/Renderer/VertexBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Graphics/Renderer/VertexBuffer.cpp.s
.PHONY : src/Engine/Graphics/Renderer/VertexBuffer.cpp.s

src/Engine/Objects/Objects.obj: src/Engine/Objects/Objects.cpp.obj
.PHONY : src/Engine/Objects/Objects.obj

# target to build an object file
src/Engine/Objects/Objects.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Objects/Objects.cpp.obj
.PHONY : src/Engine/Objects/Objects.cpp.obj

src/Engine/Objects/Objects.i: src/Engine/Objects/Objects.cpp.i
.PHONY : src/Engine/Objects/Objects.i

# target to preprocess a source file
src/Engine/Objects/Objects.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Objects/Objects.cpp.i
.PHONY : src/Engine/Objects/Objects.cpp.i

src/Engine/Objects/Objects.s: src/Engine/Objects/Objects.cpp.s
.PHONY : src/Engine/Objects/Objects.s

# target to generate assembly for a file
src/Engine/Objects/Objects.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Objects/Objects.cpp.s
.PHONY : src/Engine/Objects/Objects.cpp.s

src/Engine/Objects/Transform.obj: src/Engine/Objects/Transform.cpp.obj
.PHONY : src/Engine/Objects/Transform.obj

# target to build an object file
src/Engine/Objects/Transform.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Objects/Transform.cpp.obj
.PHONY : src/Engine/Objects/Transform.cpp.obj

src/Engine/Objects/Transform.i: src/Engine/Objects/Transform.cpp.i
.PHONY : src/Engine/Objects/Transform.i

# target to preprocess a source file
src/Engine/Objects/Transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Objects/Transform.cpp.i
.PHONY : src/Engine/Objects/Transform.cpp.i

src/Engine/Objects/Transform.s: src/Engine/Objects/Transform.cpp.s
.PHONY : src/Engine/Objects/Transform.s

# target to generate assembly for a file
src/Engine/Objects/Transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Objects/Transform.cpp.s
.PHONY : src/Engine/Objects/Transform.cpp.s

src/Engine/Scenes.obj: src/Engine/Scenes.cpp.obj
.PHONY : src/Engine/Scenes.obj

# target to build an object file
src/Engine/Scenes.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Scenes.cpp.obj
.PHONY : src/Engine/Scenes.cpp.obj

src/Engine/Scenes.i: src/Engine/Scenes.cpp.i
.PHONY : src/Engine/Scenes.i

# target to preprocess a source file
src/Engine/Scenes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Scenes.cpp.i
.PHONY : src/Engine/Scenes.cpp.i

src/Engine/Scenes.s: src/Engine/Scenes.cpp.s
.PHONY : src/Engine/Scenes.s

# target to generate assembly for a file
src/Engine/Scenes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Scenes.cpp.s
.PHONY : src/Engine/Scenes.cpp.s

src/Engine/Scripting/Components.obj: src/Engine/Scripting/Components.cpp.obj
.PHONY : src/Engine/Scripting/Components.obj

# target to build an object file
src/Engine/Scripting/Components.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Scripting/Components.cpp.obj
.PHONY : src/Engine/Scripting/Components.cpp.obj

src/Engine/Scripting/Components.i: src/Engine/Scripting/Components.cpp.i
.PHONY : src/Engine/Scripting/Components.i

# target to preprocess a source file
src/Engine/Scripting/Components.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Scripting/Components.cpp.i
.PHONY : src/Engine/Scripting/Components.cpp.i

src/Engine/Scripting/Components.s: src/Engine/Scripting/Components.cpp.s
.PHONY : src/Engine/Scripting/Components.s

# target to generate assembly for a file
src/Engine/Scripting/Components.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Scripting/Components.cpp.s
.PHONY : src/Engine/Scripting/Components.cpp.s

src/Engine/Scripting/LuaUtilities.obj: src/Engine/Scripting/LuaUtilities.cpp.obj
.PHONY : src/Engine/Scripting/LuaUtilities.obj

# target to build an object file
src/Engine/Scripting/LuaUtilities.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Scripting/LuaUtilities.cpp.obj
.PHONY : src/Engine/Scripting/LuaUtilities.cpp.obj

src/Engine/Scripting/LuaUtilities.i: src/Engine/Scripting/LuaUtilities.cpp.i
.PHONY : src/Engine/Scripting/LuaUtilities.i

# target to preprocess a source file
src/Engine/Scripting/LuaUtilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Scripting/LuaUtilities.cpp.i
.PHONY : src/Engine/Scripting/LuaUtilities.cpp.i

src/Engine/Scripting/LuaUtilities.s: src/Engine/Scripting/LuaUtilities.cpp.s
.PHONY : src/Engine/Scripting/LuaUtilities.s

# target to generate assembly for a file
src/Engine/Scripting/LuaUtilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Scripting/LuaUtilities.cpp.s
.PHONY : src/Engine/Scripting/LuaUtilities.cpp.s

src/Engine/Scripting/Scripting.obj: src/Engine/Scripting/Scripting.cpp.obj
.PHONY : src/Engine/Scripting/Scripting.obj

# target to build an object file
src/Engine/Scripting/Scripting.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Scripting/Scripting.cpp.obj
.PHONY : src/Engine/Scripting/Scripting.cpp.obj

src/Engine/Scripting/Scripting.i: src/Engine/Scripting/Scripting.cpp.i
.PHONY : src/Engine/Scripting/Scripting.i

# target to preprocess a source file
src/Engine/Scripting/Scripting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Scripting/Scripting.cpp.i
.PHONY : src/Engine/Scripting/Scripting.cpp.i

src/Engine/Scripting/Scripting.s: src/Engine/Scripting/Scripting.cpp.s
.PHONY : src/Engine/Scripting/Scripting.s

# target to generate assembly for a file
src/Engine/Scripting/Scripting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Engine/Scripting/Scripting.cpp.s
.PHONY : src/Engine/Scripting/Scripting.cpp.s

src/Game/Game.obj: src/Game/Game.cpp.obj
.PHONY : src/Game/Game.obj

# target to build an object file
src/Game/Game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Game/Game.cpp.obj
.PHONY : src/Game/Game.cpp.obj

src/Game/Game.i: src/Game/Game.cpp.i
.PHONY : src/Game/Game.i

# target to preprocess a source file
src/Game/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Game/Game.cpp.i
.PHONY : src/Game/Game.cpp.i

src/Game/Game.s: src/Game/Game.cpp.s
.PHONY : src/Game/Game.s

# target to generate assembly for a file
src/Game/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/Game/Game.cpp.s
.PHONY : src/Game/Game.cpp.s

src/PhysicsEngine/AABB.obj: src/PhysicsEngine/AABB.cpp.obj
.PHONY : src/PhysicsEngine/AABB.obj

# target to build an object file
src/PhysicsEngine/AABB.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/PhysicsEngine/AABB.cpp.obj
.PHONY : src/PhysicsEngine/AABB.cpp.obj

src/PhysicsEngine/AABB.i: src/PhysicsEngine/AABB.cpp.i
.PHONY : src/PhysicsEngine/AABB.i

# target to preprocess a source file
src/PhysicsEngine/AABB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/PhysicsEngine/AABB.cpp.i
.PHONY : src/PhysicsEngine/AABB.cpp.i

src/PhysicsEngine/AABB.s: src/PhysicsEngine/AABB.cpp.s
.PHONY : src/PhysicsEngine/AABB.s

# target to generate assembly for a file
src/PhysicsEngine/AABB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/PhysicsEngine/AABB.cpp.s
.PHONY : src/PhysicsEngine/AABB.cpp.s

src/PhysicsEngine/CollisionDetection.obj: src/PhysicsEngine/CollisionDetection.cpp.obj
.PHONY : src/PhysicsEngine/CollisionDetection.obj

# target to build an object file
src/PhysicsEngine/CollisionDetection.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/PhysicsEngine/CollisionDetection.cpp.obj
.PHONY : src/PhysicsEngine/CollisionDetection.cpp.obj

src/PhysicsEngine/CollisionDetection.i: src/PhysicsEngine/CollisionDetection.cpp.i
.PHONY : src/PhysicsEngine/CollisionDetection.i

# target to preprocess a source file
src/PhysicsEngine/CollisionDetection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/PhysicsEngine/CollisionDetection.cpp.i
.PHONY : src/PhysicsEngine/CollisionDetection.cpp.i

src/PhysicsEngine/CollisionDetection.s: src/PhysicsEngine/CollisionDetection.cpp.s
.PHONY : src/PhysicsEngine/CollisionDetection.s

# target to generate assembly for a file
src/PhysicsEngine/CollisionDetection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/PhysicsEngine/CollisionDetection.cpp.s
.PHONY : src/PhysicsEngine/CollisionDetection.cpp.s

src/PhysicsEngine/RigidBody.obj: src/PhysicsEngine/RigidBody.cpp.obj
.PHONY : src/PhysicsEngine/RigidBody.obj

# target to build an object file
src/PhysicsEngine/RigidBody.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/PhysicsEngine/RigidBody.cpp.obj
.PHONY : src/PhysicsEngine/RigidBody.cpp.obj

src/PhysicsEngine/RigidBody.i: src/PhysicsEngine/RigidBody.cpp.i
.PHONY : src/PhysicsEngine/RigidBody.i

# target to preprocess a source file
src/PhysicsEngine/RigidBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/PhysicsEngine/RigidBody.cpp.i
.PHONY : src/PhysicsEngine/RigidBody.cpp.i

src/PhysicsEngine/RigidBody.s: src/PhysicsEngine/RigidBody.cpp.s
.PHONY : src/PhysicsEngine/RigidBody.s

# target to generate assembly for a file
src/PhysicsEngine/RigidBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/PhysicsEngine/RigidBody.cpp.s
.PHONY : src/PhysicsEngine/RigidBody.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/stb_image.obj: src/stb_image.cpp.obj
.PHONY : src/stb_image.obj

# target to build an object file
src/stb_image.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/stb_image.cpp.obj
.PHONY : src/stb_image.cpp.obj

src/stb_image.i: src/stb_image.cpp.i
.PHONY : src/stb_image.i

# target to preprocess a source file
src/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/stb_image.cpp.i
.PHONY : src/stb_image.cpp.i

src/stb_image.s: src/stb_image.cpp.s
.PHONY : src/stb_image.s

# target to generate assembly for a file
src/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sapphire-Engine.dir/build.make CMakeFiles/Sapphire-Engine.dir/src/stb_image.cpp.s
.PHONY : src/stb_image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Sapphire-Engine"
	@echo "... cmake_pch.hxx.gch"
	@echo "... cmake_pch.hxx.i"
	@echo "... cmake_pch.hxx.s"
	@echo "... include/Imgui/ImGuiFileDialog.obj"
	@echo "... include/Imgui/ImGuiFileDialog.i"
	@echo "... include/Imgui/ImGuiFileDialog.s"
	@echo "... include/Imgui/ImGuizmo.obj"
	@echo "... include/Imgui/ImGuizmo.i"
	@echo "... include/Imgui/ImGuizmo.s"
	@echo "... include/Imgui/imgui.obj"
	@echo "... include/Imgui/imgui.i"
	@echo "... include/Imgui/imgui.s"
	@echo "... include/Imgui/imgui_draw.obj"
	@echo "... include/Imgui/imgui_draw.i"
	@echo "... include/Imgui/imgui_draw.s"
	@echo "... include/Imgui/imgui_impl_glfw.obj"
	@echo "... include/Imgui/imgui_impl_glfw.i"
	@echo "... include/Imgui/imgui_impl_glfw.s"
	@echo "... include/Imgui/imgui_impl_opengl3.obj"
	@echo "... include/Imgui/imgui_impl_opengl3.i"
	@echo "... include/Imgui/imgui_impl_opengl3.s"
	@echo "... include/Imgui/imgui_stdlib.obj"
	@echo "... include/Imgui/imgui_stdlib.i"
	@echo "... include/Imgui/imgui_stdlib.s"
	@echo "... include/Imgui/imgui_tables.obj"
	@echo "... include/Imgui/imgui_tables.i"
	@echo "... include/Imgui/imgui_tables.s"
	@echo "... include/Imgui/imgui_widgets.obj"
	@echo "... include/Imgui/imgui_widgets.i"
	@echo "... include/Imgui/imgui_widgets.s"
	@echo "... include/Imgui/implot.obj"
	@echo "... include/Imgui/implot.i"
	@echo "... include/Imgui/implot.s"
	@echo "... include/Imgui/implot_items.obj"
	@echo "... include/Imgui/implot_items.i"
	@echo "... include/Imgui/implot_items.s"
	@echo "... src/Application/Application.obj"
	@echo "... src/Application/Application.i"
	@echo "... src/Application/Application.s"
	@echo "... src/Editor/DebugDraw.obj"
	@echo "... src/Editor/DebugDraw.i"
	@echo "... src/Editor/DebugDraw.s"
	@echo "... src/Editor/Editor.obj"
	@echo "... src/Editor/Editor.i"
	@echo "... src/Editor/Editor.s"
	@echo "... src/Editor/ImGuiWindows.obj"
	@echo "... src/Editor/ImGuiWindows.i"
	@echo "... src/Editor/ImGuiWindows.s"
	@echo "... src/Editor/UI/FileExplorer/File.obj"
	@echo "... src/Editor/UI/FileExplorer/File.i"
	@echo "... src/Editor/UI/FileExplorer/File.s"
	@echo "... src/Editor/UI/FileExplorer/FileExplorer.obj"
	@echo "... src/Editor/UI/FileExplorer/FileExplorer.i"
	@echo "... src/Editor/UI/FileExplorer/FileExplorer.s"
	@echo "... src/Editor/UI/ProjectManager.obj"
	@echo "... src/Editor/UI/ProjectManager.i"
	@echo "... src/Editor/UI/ProjectManager.s"
	@echo "... src/Editor/Variables.obj"
	@echo "... src/Editor/Variables.i"
	@echo "... src/Editor/Variables.s"
	@echo "... src/Engine/Engine.obj"
	@echo "... src/Engine/Engine.i"
	@echo "... src/Engine/Engine.s"
	@echo "... src/Engine/Graphics/Animation.obj"
	@echo "... src/Engine/Graphics/Animation.i"
	@echo "... src/Engine/Graphics/Animation.s"
	@echo "... src/Engine/Graphics/Grid.obj"
	@echo "... src/Engine/Graphics/Grid.i"
	@echo "... src/Engine/Graphics/Grid.s"
	@echo "... src/Engine/Graphics/Renderer.obj"
	@echo "... src/Engine/Graphics/Renderer.i"
	@echo "... src/Engine/Graphics/Renderer.s"
	@echo "... src/Engine/Graphics/Renderer/FrameBuffer.obj"
	@echo "... src/Engine/Graphics/Renderer/FrameBuffer.i"
	@echo "... src/Engine/Graphics/Renderer/FrameBuffer.s"
	@echo "... src/Engine/Graphics/Renderer/IndexBuffer.obj"
	@echo "... src/Engine/Graphics/Renderer/IndexBuffer.i"
	@echo "... src/Engine/Graphics/Renderer/IndexBuffer.s"
	@echo "... src/Engine/Graphics/Renderer/Shader.obj"
	@echo "... src/Engine/Graphics/Renderer/Shader.i"
	@echo "... src/Engine/Graphics/Renderer/Shader.s"
	@echo "... src/Engine/Graphics/Renderer/Texture.obj"
	@echo "... src/Engine/Graphics/Renderer/Texture.i"
	@echo "... src/Engine/Graphics/Renderer/Texture.s"
	@echo "... src/Engine/Graphics/Renderer/VertexArray.obj"
	@echo "... src/Engine/Graphics/Renderer/VertexArray.i"
	@echo "... src/Engine/Graphics/Renderer/VertexArray.s"
	@echo "... src/Engine/Graphics/Renderer/VertexBuffer.obj"
	@echo "... src/Engine/Graphics/Renderer/VertexBuffer.i"
	@echo "... src/Engine/Graphics/Renderer/VertexBuffer.s"
	@echo "... src/Engine/Objects/Objects.obj"
	@echo "... src/Engine/Objects/Objects.i"
	@echo "... src/Engine/Objects/Objects.s"
	@echo "... src/Engine/Objects/Transform.obj"
	@echo "... src/Engine/Objects/Transform.i"
	@echo "... src/Engine/Objects/Transform.s"
	@echo "... src/Engine/Scenes.obj"
	@echo "... src/Engine/Scenes.i"
	@echo "... src/Engine/Scenes.s"
	@echo "... src/Engine/Scripting/Components.obj"
	@echo "... src/Engine/Scripting/Components.i"
	@echo "... src/Engine/Scripting/Components.s"
	@echo "... src/Engine/Scripting/LuaUtilities.obj"
	@echo "... src/Engine/Scripting/LuaUtilities.i"
	@echo "... src/Engine/Scripting/LuaUtilities.s"
	@echo "... src/Engine/Scripting/Scripting.obj"
	@echo "... src/Engine/Scripting/Scripting.i"
	@echo "... src/Engine/Scripting/Scripting.s"
	@echo "... src/Game/Game.obj"
	@echo "... src/Game/Game.i"
	@echo "... src/Game/Game.s"
	@echo "... src/PhysicsEngine/AABB.obj"
	@echo "... src/PhysicsEngine/AABB.i"
	@echo "... src/PhysicsEngine/AABB.s"
	@echo "... src/PhysicsEngine/CollisionDetection.obj"
	@echo "... src/PhysicsEngine/CollisionDetection.i"
	@echo "... src/PhysicsEngine/CollisionDetection.s"
	@echo "... src/PhysicsEngine/RigidBody.obj"
	@echo "... src/PhysicsEngine/RigidBody.i"
	@echo "... src/PhysicsEngine/RigidBody.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/stb_image.obj"
	@echo "... src/stb_image.i"
	@echo "... src/stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

