//PRECOMPILED HEADER


#include <math.h>
#include <iostream>
#include <filesystem>
#include <string>
#include <cstring>
#include <iostream>
#include <memory>
#include <string>
#include <fstream>
#include "glm/glm.hpp"
#include "glm/gtc/matrix_transform.hpp"
#include <sstream>
#include <iostream>
#include <array>
#include <vector>
#include <functional>
#include <iostream>
#include <string>
#include <vector>
#include <typeinfo>
#include <map>
#include <queue>
#include <variant>
#include <optional>
#include <unordered_map>
#include <glm/gtc/type_ptr.hpp>
#define GLM_ENABLE_EXPERIMENTAL
#include <glm/gtx/quaternion.hpp>
#include <glm/gtx/matrix_decompose.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <random>
